name: Generate Release Notes for PR

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - master

jobs:
  generate-release-notes:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Download Auto Release Note CLI
        run: |
          # Download from distribution repository
          VERSION="latest"
          if [ "$VERSION" == "latest" ]; then
            # Get latest release URL
            DOWNLOAD_URL=$(curl -s https://api.github.com/repos/papyrus-digital/auto-release-cli-distribution/releases/latest | grep "browser_download_url.*linux_amd64.tar.gz" | cut -d '"' -f 4)
          else
            DOWNLOAD_URL="https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/${VERSION}/arn_${VERSION}_linux_amd64.tar.gz"
          fi
          curl -LO "$DOWNLOAD_URL"
          tar -xzf arn_*_linux_amd64.tar.gz
          chmod +x arn
          sudo mv arn /usr/local/bin/

      - name: Generate Release Notes for PR
        id: generate
        env:
          AUTO_RELEASE_TOKEN: ${{ secrets.AUTO_RELEASE_TOKEN }}
          AUTO_RELEASE_PROJECT_ID: ${{ secrets.AUTO_RELEASE_PROJECT_ID }}
        run: |
          BASE_SHA=${{ github.event.pull_request.base.sha }}
          HEAD_SHA=${{ github.event.pull_request.head.sha }}
          
          RELEASE_URL=$(arn generate \
            --non-interactive \
            --mode commit \
            --from $BASE_SHA \
            --to $HEAD_SHA \
            --template "Standard Changelog" \
            --output-url)
          
          echo "url=$RELEASE_URL" >> $GITHUB_OUTPUT
          echo "Release notes generated: $RELEASE_URL"

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const url = '${{ steps.generate.outputs.url }}';
            const body = `## 📝 Release Notes Generated
            
            Release notes have been automatically generated for this PR!
            
            **View Release Notes:** [Click here](${url})
            
            ---
            *Generated by Auto Release Note CLI*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

